"$schema": "http://json-schema.org/draft-07/schema#"
"$id": "https://schemata.nostr.watch/note/kind/9905"
title: "Business Transaction Attestation Event (Kind 9905)"
description: "Full event schema for transaction.attestation (kind 9905) - signed event sent by business to attest customer transaction"
allOf:
  - type: object
    properties:
      id:
        type: string
        pattern: "^[a-f0-9]{64}$"
        description: "Deterministic event hash as defined in NIP-01"
        errorMessage: "id must be a 64-character lowercase hex string"
      content:
        type: string
        errorMessage: "content must be a string"
        description: "The content of the note"
      created_at:
        type: integer
        errorMessage: "created_at must be a timestamp expressed in seconds (not milliseconds)"
        description: "The timestamp of the note creation"
      kind:
        type: integer
      pubkey:
        type: string
        pattern: "^[a-f0-9]{64}$"
        errorMessage: "pubkey must be a secp256k1 public key"
        description: "The public key of the note's author"
      tags:
        type: array
        errorMessage: "tags must be an array of valid tag tuples"
        description: "The tags of the note"
        items:
          type: array
          minItems: 1
          items:
            type: string
      sig:
        type: string
        pattern: "^[a-f0-9]{128}$"
        errorMessage: "sig must be a 128-character lowercase hex string"
        description: "Signature of the event"
    required:
      - content
      - created_at
      - kind
      - tags
      - sig
    additionalProperties: false
  - type: object
    properties:
      kind:
        const: 9905
        description: "Kind 9905 identifies a business transaction attestation"
        errorMessage: "kind must equal 9905"
      id:
        type: string
        pattern: "^[a-f0-9]{64}$"
        description: "Deterministic event hash as defined in NIP-01"
        errorMessage: "id must be a 64-character lowercase hex string"
      pubkey:
        type: string
        pattern: "^[a-f0-9]{64}$"
        description: "Business public key"
        errorMessage: "pubkey must be a 64-character lowercase hex string (secp256k1 public key)"
      content:
        type: string
        const: ""
        description: "Content must be empty string"
        errorMessage: "content must be an empty string"
      tags:
        type: array
        items:
          type: array
          minItems: 1
          items:
            type: string
        minItems: 5
        allOf:
          - contains:
              type: array
              minItems: 2
              maxItems: 2
              items:
                - const: "p"
                  description: "Tag identifier"
                - type: string
                  pattern: "^[a-f0-9]{64}$"
                  description: "Customer public key"
                  errorMessage: "p tag value must be a 64-character lowercase hex string"
              additionalItems: false
            errorMessage:
              contains: "tags must include a p tag with format ['p', '<customerPublicKey>']"
          - contains:
              type: array
              minItems: 4
              maxItems: 4
              items:
                - const: "e"
                  description: "Tag identifier"
                - type: string
                  pattern: "^[a-f0-9]{64}$"
                  description: "Unsigned rumor ID of the original reservation.request (kind 9901) - connects message to reservation thread"
                  errorMessage: "e tag value must be a 64-character lowercase hex string (unsigned rumor ID)"
                - const: ""
                  description: "Empty string (relay URL not needed for rumors)"
                - const: "root"
                  description: "Marker indicating this references the root event"
              additionalItems: false
            errorMessage:
              contains: "tags must include an e tag with format ['e', '<unsigned-9901-rumor.id>', '', 'root']"
          - contains:
              type: array
              minItems: 2
              maxItems: 2
              items:
                - const: "time"
                  description: "Tag identifier"
                - type: string
                  pattern: "^[0-9]+$"
                  description: "Inclusive reservation start Unix timestamp in seconds"
                  errorMessage: "time must be a Unix timestamp in seconds"
              additionalItems: false
            errorMessage:
              contains: "tags must include a time tag with format ['time', '<unix timestamp in seconds>']"
          - contains:
              type: array
              minItems: 2
              maxItems: 2
              items:
                - const: "tzid"
                  description: "Tag identifier"
                - type: string
                  description: "Time zone of the reservation time Unix timestamp, as defined by the IANA Time Zone Database (e.g., America/Costa_Rica)"
                  errorMessage: "tzid must be a valid IANA Time Zone Database identifier"
              additionalItems: false
            errorMessage:
              contains: "tags must include a tzid tag with format ['tzid', '<IANA Time Zone Database identifier>']"
          - contains:
              type: array
              minItems: 2
              maxItems: 2
              items:
                - const: "qts_labels"
                  description: "Tag identifier"
                - type: string
                  description: "Comma separated list of labels for QTS review"
                  errorMessage: "qts_labels must be a comma separated list of labels"
              additionalItems: false
            errorMessage:
              contains: "tags must include a qts_labels tag with format ['qts_labels', '<label1, label2, ..., labelN>']"
    required:
      - kind
      - id
      - pubkey
      - sig
