"$id": "https://schemata.nostr.watch/note/tag/verified"
"$schema": "http://json-schema.org/draft-07/schema#"
title: "Verified Tag"
description: "Tag containing base64-encoded kind:9905 transaction attestation event for verified business reviews (NIP-RP)"
allOf:
  - $ref: "@/tag.yaml"
  - type: array
    minItems: 2
    maxItems: 2
    items:
      - const: "verified"
        description: "Tag identifier"
      - type: string
        pattern: "^[A-Za-z0-9+/]+=*$"
        description: "Base64 encoded kind:9905 transaction attestation event"
        errorMessage: "verified tag value must be a valid base64 encoded string"
    additionalItems: false

